# Generated by Django 3.2.12 on 2022-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
