# Generated by Django 3.2.12 on 2022-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20220504_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cash',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_create_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
