# Generated by Django 3.2.12 on 2022-05-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20220502_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
