# Generated by Django 3.2.12 on 2022-05-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_rename_mobile_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp',
            new_name='verifyCode',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='otp_create_time',
            new_name='verifyCode_create_time',
        ),
    ]
