# Generated by Django 3.2.12 on 2022-05-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedsms',
            name='to_users',
            field=models.ManyToManyField(related_name='sms_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedsms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedrecommendedshop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='usedrecommendedshop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedrecommendedproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='usedrecommendedproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usedbanner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportshop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='reportshop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='banner_packs',
            field=models.ManyToManyField(blank=True, to='services.CartBanner'),
        ),
        migrations.AddField(
            model_name='order',
            name='recommended_product_pack',
            field=models.ManyToManyField(blank=True, to='services.CartRecommendedProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='recommended_shop_pack',
            field=models.ManyToManyField(blank=True, to='services.CartRecommendedShop'),
        ),
        migrations.AddField(
            model_name='order',
            name='sms_packs',
            field=models.ManyToManyField(blank=True, to='services.CartSms'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyshopview',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop'),
        ),
        migrations.AddField(
            model_name='dailyproductview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='cartsms',
            name='sms_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.smspack'),
        ),
        migrations.AddField(
            model_name='cartsms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartrecommendedshop',
            name='recommended_shop_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.recommendedshoppack'),
        ),
        migrations.AddField(
            model_name='cartrecommendedshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartrecommendedproduct',
            name='recommended_product_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.recommendedproductpack'),
        ),
        migrations.AddField(
            model_name='cartrecommendedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartbanner',
            name='banner_pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bannerpack'),
        ),
        migrations.AddField(
            model_name='cartbanner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
