# Generated by Django 3.2.12 on 2022-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsorder',
            name='to_users',
        ),
        migrations.AddField(
            model_name='smsorder',
            name='to_users',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
