# Generated by Django 2.2.28 on 2022-05-16 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_customsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedsms',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_used_sms', to=settings.AUTH_USER_MODEL),
        ),
    ]
