# Generated by Django 2.2.28 on 2022-05-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220516_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsms',
            name='users',
        ),
        migrations.AddField(
            model_name='customsms',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
