# Generated by Django 3.2.12 on 2022-05-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220503_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='banner_packs',
            field=models.ManyToManyField(blank=True, to='services.CartBanner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sms_packs',
            field=models.ManyToManyField(blank=True, to='services.CartSms'),
        ),
    ]
