# Generated by Django 2.2.28 on 2022-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220516_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproductview',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyshopview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyshopview',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
