# Generated by Django 2.2.28 on 2022-05-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20220516_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproductview',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dailyproductview',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='dailyshopview',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dailyshopview',
            name='modified',
        ),
    ]
