# Generated by Django 3.2.12 on 2022-05-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20220504_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
