# Generated by Django 3.2.12 on 2022-05-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_ticket_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
