# Generated by Django 3.2.12 on 2022-05-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_ticket_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproductview',
            name='user_ip',
        ),
        migrations.RemoveField(
            model_name='dailyshopview',
            name='user_ip',
        ),
    ]
