# Generated by Django 2.2.28 on 2022-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220514_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='shops-banners'),
        ),
    ]
