# Generated by Django 4.0.4 on 2022-04-22 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo',
            new_name='image',
        ),
    ]
