# Generated by Django 3.2.12 on 2022-05-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shops'),
        ),
    ]
