# Generated by Django 3.2.12 on 2022-05-11 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
