# Generated by Django 2.2.28 on 2022-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='banner',
        ),
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, default='cover/1713248.jpg', null=True, upload_to='cover'),
        ),
    ]
