# Generated by Django 2.2.28 on 2022-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220514_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(default='cover/cover.jpg', null=True, upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='shops/image.jpg', upload_to='shops'),
        ),
    ]
