# Generated by Django 2.2.28 on 2022-04-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220424_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(to='shop.ProductImage'),
        ),
    ]
