# Generated by Django 3.2.12 on 2022-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
    ]
