# Generated by Django 3.2.12 on 2022-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off',
            field=models.IntegerField(default=0),
        ),
    ]
