# Generated by Django 2.2.28 on 2022-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220426_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(default='media\\cover\\default_cover.jpg', upload_to='cover'),
        ),
    ]
