# Generated by Django 3.2.12 on 2022-05-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productcomment_is_bad'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hide',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
