# Generated by Django 3.2.12 on 2022-05-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220502_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
