# Generated by Django 3.2.12 on 2022-05-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220503_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cover',
        ),
    ]
