# Generated by Django 3.2.12 on 2022-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_reportproduct_reportshop_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='reportproduct',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportshop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='reportshop',
            name='user',
        ),
        migrations.RemoveField(
            model_name='smsorder',
            name='to_users',
        ),
        migrations.RemoveField(
            model_name='smsorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='BannerAd',
        ),
        migrations.DeleteModel(
            name='ReportProduct',
        ),
        migrations.DeleteModel(
            name='ReportShop',
        ),
        migrations.DeleteModel(
            name='SmsOrder',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
